### ISSUE TITLE
matchDetectionRulesAgainstUA does a linear scan of all regex

### ISSUE THREAD

**Issue by Xon** [cclaerhout/xen_BrowserDetection#1]
I noticed during profiling that this function was taking ~5ms under xhprof, with ~127 calls to Sedo_DetectBrowser_Helper_MobileDetect::match().

Would it make sense to compile the regexs into a single regex on 1st access, and cache it into the XF caching system? This array of regex's is only going to get bigger.

**Comment by Xon** [comment]
In https://github.com/Xon/xen_BrowserDetection/commit/db435128a75c6b74c537d217ab91766fd5e6ae60 Doesn't appear to make a difference in benchmarking. preg_match is still taking ~5ms or so.

**Comment by cclaerhout** [comment]
It certainly comes from the calls of the class "Sedo_DetectBrowser_Listener_Visitor"  ; Do the 127 calls  occur when the browser has a mobile user agent?

**Comment by Xon** [comment]
No, this is a worse case of when a desktop client is hit.

**Comment by cclaerhout** [comment]
I had a look, it can't be optimized, since the call is made from isMobile() then the script checks all mobile devices. I try to make a meta regex with all devices, but the request time is the same. The only thing that might be slightly optimized would only be for mobile devices: implement a stack of UA and result for the match() function, but it wouldn't make a big difference.

**Comment by Xon** [comment]
Yeah, that is about the conclusion I came to as well.

About the only way to make it faster is to store the UA after some minor fuzzing and do direct query matches in the database to try to reduce it.
